from __future__ import annotations

from pathlib import Path
from typing import Any


def render_wireguard_config(profile: dict[str, Any]) -> str:
    interface = profile["wireguard"]["interface"]
    peer = profile["wireguard"]["peer"]
    lines = [
        "# Generated by quantum-weighted-workflow.",
        "# Review before use. This file does not activate a tunnel.",
        "[Interface]",
        f"Address = {interface['address']}",
        f"PrivateKey = {interface['private_key_ref']}",
    ]
    if interface.get("dns"):
        lines.append(f"DNS = {', '.join(interface['dns'])}")
    lines.extend(
        [
            "",
            "[Peer]",
            f"PublicKey = {peer['public_key']}",
            f"Endpoint = {peer['endpoint']}",
            f"AllowedIPs = {', '.join(peer['allowed_ips'])}",
        ]
    )
    if peer.get("persistent_keepalive") is not None:
        lines.append(f"PersistentKeepalive = {peer['persistent_keepalive']}")
    return "\n".join(lines) + "\n"


def write_wireguard_config(profile: dict[str, Any], output: Path) -> Path:
    output.write_text(render_wireguard_config(profile), encoding="utf-8")
    return output


def activation_plan(profile: dict[str, Any], config_path: Path) -> dict[str, Any]:
    return {
        "backend": "wireguard",
        "mode": "manual-activation-required",
        "profile": profile["endpoint_alias"],
        "config_path": str(config_path),
        "review_steps": [
            "Replace placeholder key references with secrets from your VPN client or secret manager.",
            "Verify the endpoint, public key, allowed IPs, DNS policy, and routing scope.",
            "Import the config into a reviewed WireGuard-compatible client.",
            "Use a provider or implementation with reviewed post-quantum or hybrid key-establishment support when available.",
        ],
        "not_performed": [
            "No tunnel was started.",
            "No route was changed.",
            "No DNS setting was changed.",
            "No firewall rule was changed.",
        ],
    }
